spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/register_platform
    username: postgres
    password: nikolaeva0628
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
server:
  port: 8081
